/** Final frame and autosize adapted from OpenIntelligentUI, f6e4388 (MIT).
 * No design-system imports, remote assets, tools or host styles are exposed.
 */
export const RESIZE_MESSAGE_TYPE = '__ogui_resize';
export const ERROR_MESSAGE_TYPE = '__ogui_report_error';
export const CSP_META_TAG = `<meta http-equiv="Content-Security-Policy" content="default-src 'none'; script-src 'unsafe-inline' 'unsafe-eval'; style-src 'unsafe-inline'; img-src data: blob:; font-src data:; connect-src 'none'; base-uri 'none'; form-action 'none'">`;

const ERROR_LISTENERS_JS = `
(function () {
  function failed(event) {
    if (event && event.preventDefault) event.preventDefault();
    parent.postMessage({type: '${ERROR_MESSAGE_TYPE}'}, '*');
  }
  window.addEventListener('error', failed);
  window.addEventListener('unhandledrejection', failed);
})();`;

function styleTag(css: string): string {
  // Keep CSS text from closing its raw-text element and inserting HTML.
  return `<style>${css.replace(/<\/style/gi, '<\\/style')}</style>`;
}

export function buildFinalFrameContent(html: string, css = '', themeCss = ''): string {
  // Our head always precedes generated bytes, including a model-supplied full
  // document or a script before its own head. Websandbox inserts its trusted
  // bootstrap immediately after this exact <head>; CSP precedes model content.
  return `<!DOCTYPE html><html><head>${CSP_META_TAG}<meta charset="utf-8">${styleTag('html,body{margin:0;padding:0;min-height:0;height:auto;overflow:auto}body{display:flow-root}')}${styleTag(themeCss)}${styleTag(css)}<script>${ERROR_LISTENERS_JS}</script></head><body>${html}</body></html>`;
}

export const MEASUREMENT_JS = `
(function () {
  if (window.__oguiResizeInstalled) return;
  window.__oguiResizeInstalled = true;
  var style = document.createElement('style');
  style.textContent = 'html,body{height:auto!important;min-height:0!important;overflow:auto!important}';
  document.head.appendChild(style);
  function reportHeight() {
    // body.scrollHeight is floored by the iframe viewport in some browsers;
    // its auto-height box can shrink after content is removed.
    var body = document.body;
    var rect = body.getBoundingClientRect();
    var cs = getComputedStyle(body);
    var h = rect.height + (parseFloat(cs.marginTop)||0) + (parseFloat(cs.marginBottom)||0);
    for (var node of body.querySelectorAll('*')) {
      // Closed details can retain layout boxes for their hidden descendants.
      if (typeof node.checkVisibility === 'function' && !node.checkVisibility()) continue;
      var closed = node.closest('details:not([open])');
      if (closed && node !== closed && !closed.querySelector('summary')?.contains(node)) continue;
      var child = node.getBoundingClientRect();
      h = Math.max(h, child.bottom - rect.top);
    }
    parent.postMessage({type: '${RESIZE_MESSAGE_TYPE}', height: Math.ceil(h)}, '*');
  }
  var scheduled = false;
  function queueHeight() {
    if (scheduled) return;
    scheduled = true;
    requestAnimationFrame(function () { scheduled = false; reportHeight(); });
  }
  new ResizeObserver(queueHeight).observe(document.body);
  new MutationObserver(queueHeight).observe(document.body, {subtree:true,childList:true,attributes:true,characterData:true});
  window.addEventListener('resize', queueHeight);
  window.addEventListener('load', queueHeight);
  document.addEventListener('load', queueHeight, true);
  if (document.fonts) document.fonts.ready.then(queueHeight).catch(function() {});
  queueHeight();
})();`;
